### ISSUE TITLE
Change Property name componentRef

### ISSUE THREAD

**Issue by qkreltms** [llorentegerman/simple-flexbox#10]
You may think the property name ```componentRef``` is not  a familiar word. 

You may want to change it to ```ref```, but It seemed Class Component does not allowed to use ```ref``` as a prop's name. (https://reactjs.org/warnings/special-props.html)

You may want to change it to Functional Component with ```React.forwadRef()``` (for this we should update react >= 16.3 )

**Comment by llorentegerman** [comment]
I don't think it's necessary at the moment, but we can think about that in the future.
Thank you!
