### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by maartenafink** [llorentegerman/simple-flexbox#12]
I'm having this issue while building my Gatsby website, any idea how to fix it?

`

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html

  497 |                     return _extends({}, style, window.innerWidth <= +key ? { flexDirection: value } : {});
  498 |                 }
> 499 |                 return _extends({}, style, window.innerWidth <= +key ? value : {});
      |                                   ^
  500 |             }, {});
  501 | 
  502 |             var classNames = ((className || '') + ' ' + breakpointsClassNames.join(' ')).trim();

  WebpackError: ReferenceError: window is not defined
  
  - index.js:499 
    node_modules/simple-flexbox/build/index.js:499:35
  
  - index.js:485 Layout.render
    node_modules/simple-flexbox/build/index.js:485:14

`

![image](https://user-images.githubusercontent.com/31848800/72665332-9fe52c80-3a07-11ea-86b9-3437bdee996b.png)

**Comment by llorentegerman** [comment]
If you are using SSR, windows or document don't exists AFAIK
https://sitecore.stackexchange.com/questions/16437/ssr-issue-window-not-defined

are you using `breakpoints`? what happens if you don't? the problem is fixed?

**Comment by maartenafink** [comment]
> If you are using SSR, windows or document don't exists AFAIK
> https://sitecore.stackexchange.com/questions/16437/ssr-issue-window-not-defined
> 
> are you using `breakpoints`? what happens if you don't? the problem is fixed?

Found it, thanks!
