### ISSUE TITLE
webpack in prod dependencies

### ISSUE THREAD

**Issue by p-somers** [llorentegerman/simple-flexbox#16]
Can webpack be moved to dev-dependencies? This is causing issues in my project which uses a newer version of react

**Comment by jc-hcl** [comment]
@llorentegerman please consider this issue, OSS scanning tools consider all the transitive dependencies of webpack as being shipped code which results in a large number of false-positive alerts being raised.

**Comment by llorentegerman** [comment]
@jc-hcl are you using the latest version of this package? (v2.3.3)

**Comment by jc-hcl** [comment]
Was checking back on this defect and PR which were open, but can see it's been fixed in the 2.3.3 release, many thanks!
