### ISSUE TITLE
Adding <form> element as semantic element 

### ISSUE THREAD

**Issue by qkreltms** [llorentegerman/simple-flexbox#6]
How about adding **form** element as a semantic element?
It uses as a container of inputs so we should add it into our code.

```
 element: PropTypes.oneOf([**_'form',_** 'article', 'aside', 'div', 'figure', 'footer', 'header', 'main', 'nav', 'section'])
```

**Comment by llorentegerman** [comment]
Included in **v2.2.0**
[changes](https://github.com/llorentegerman/simple-flexbox/commit/49c5244617c4b6fbfdbf2cbac924a41b51147eb4)
